import type { AppLocale } from "@/lib/i18n/config";

type Section = { title: string; text: string };
type Body = {
  about: { badge: string; title: string; intro: string; whyTitle: string; whyText: string; whoTitle: string; whoText: string; listTitle: string; list: string[] };
  contact: { badge: string; title: string; intro: string; primary: string; response: string; topicsTitle: string; topics: Section[] };
  contracts: { badge: string; title: string; intro: string; note: string; comingSoon: string; open: string };
  privacy: { title: string; intro: string; sections: Section[]; questionsTitle: string; questionsText: string; contactPage: string };
  terms: { title: string; intro: string; sections: Section[]; contactTitle: string; contactText: string; contactPage: string };
  blog: { badge: string; title: string; intro: string; latestTitle: string; latestIntro: string; read: string };
  calculators: { badge: string; title: string; intro: string; open: string; groups: { heading: string; intro: string }[] };
};

const en: Body = {
  about: { badge: "About ProfitHub", title: "Built to help you make better business decisions with numbers", intro: "ProfitHub is a collection of simple, powerful business calculators designed for freelancers, founders, ecommerce sellers, and operators who want clarity in pricing, margins, and decisions.", whyTitle: "Why ProfitHub exists", whyText: "Most people run their business on guesswork. ProfitHub exists to replace guessing with numbers.", whoTitle: "Who it's for", whoText: "Freelancers, SaaS founders, ecommerce sellers, and small business owners who want smarter, data-driven decisions.", listTitle: "What you can do with ProfitHub", list: ["Calculate real profit", "Set better freelance pricing", "Understand SaaS MRR and growth", "Analyze subscription leaks and churn", "Structure revenue share deals", "Make faster decisions with real data"] },
  contact: { badge: "Contact ProfitHub", title: "Talk with the ProfitHub team", intro: "We build free calculators, practical guides, and lightweight deal tools. If you need help, have a suggestion, or want to collaborate, we'd love to hear from you.", primary: "Primary contact", response: "Typical response time: within 1–2 business days.", topicsTitle: "What you can contact us for", topics: [{ title: "Calculator support", text: "Questions about calculator inputs, outputs, or result interpretation." }, { title: "Tool suggestions", text: "Request new calculators, use cases, or workflow improvements." }, { title: "Bug reports", text: "Report incorrect calculations, UX issues, or content bugs with details." }, { title: "Partnership inquiries", text: "Explore collaborations, integrations, and distribution partnerships." }] },
  contracts: { badge: "ProfitHub Deal Engine", title: "Contract Generators", intro: "Create practical business contract templates in minutes.", note: "Templates are for operational support and are not legal advice.", comingSoon: "Coming Soon", open: "Open Generator" },
  privacy: { title: "Privacy Policy", intro: "This page explains what data is collected on ProfitHub and how it is used.", sections: [{ title: "What data we collect", text: "ProfitHub calculators run in your browser and usually do not require account creation for basic use. We may collect standard telemetry like page views, browser/device data, and interaction events." }, { title: "Analytics and performance monitoring", text: "ProfitHub uses analytics/performance tools including Google Analytics, Microsoft Clarity, Vercel Analytics, and Vercel Speed Insights." }, { title: "Cookies and tracking", text: "These providers may use cookies or similar technologies to measure traffic and experience trends." }, { title: "Third-party links and tools", text: "ProfitHub may link to external services. We are not responsible for third-party privacy practices." }, { title: "Policy updates", text: "We may update this policy as the product evolves. The latest version is always published at" }], questionsTitle: "Privacy questions", questionsText: "For privacy questions or requests, email contact@profithub.cloud or visit our", contactPage: "contact page" },
  terms: { title: "Terms of Service", intro: "These terms describe how ProfitHub calculators, blog content, and contract/deal tools may be used.", sections: [{ title: "Acceptance of Terms", text: "By using ProfitHub, you agree to these Terms of Service." }, { title: "Informational Use Only", text: "Tools and templates are for informational and operational support purposes only and are not legal, financial, or tax advice." }, { title: "No Guarantees", text: "Calculator outputs are estimates based on user inputs. We do not guarantee specific outcomes." }, { title: "User Responsibility", text: "You are responsible for evaluating results and decisions before acting." }, { title: "Intellectual Property and Usage", text: "Website content, branding, and interfaces are owned by ProfitHub unless stated otherwise." }, { title: "Limitation of Liability", text: "To the extent permitted by law, ProfitHub is not liable for damages resulting from use of this website." }, { title: "Updates to Terms", text: "We may update these terms over time. Continued use after updates means acceptance." }], contactTitle: "Contact", contactText: "Questions about these terms can be sent to contact@profithub.cloud. You can also use our", contactPage: "contact page" },
  blog: { badge: "ProfitHub Blog", title: "Business calculators, pricing, and profitability insights", intro: "Read practical articles about pricing, margins, recurring revenue, project profitability, and better business decisions.", latestTitle: "Latest Articles", latestIntro: "Explore guides connected to ProfitHub calculators and decision tools.", read: "Read article" },
  calculators: { badge: "ProfitHub Calculators Hub", title: "Free business calculators for profitability, pricing, and decision-making", intro: "Explore every ProfitHub calculator in one place.", open: "Open", groups: [{ heading: "Ecommerce Calculators", intro: "Validate offer economics, improve contribution margin, and avoid scaling low-profit campaigns." }, { heading: "SaaS Calculators", intro: "Track recurring revenue quality, leakage, and prioritization impact." }, { heading: "Freelancer & Deal Tools", intro: "Set sustainable pricing, evaluate project economics, and negotiate fair terms." }] },
};

const ar: Body = {
  ...en,
  about: { ...en.about, badge: "حول ProfitHub", title: "مبني لمساعدتك على اتخاذ قرارات أعمال أفضل بالأرقام", intro: "ProfitHub مجموعة من حاسبات الأعمال البسيطة والقوية للمستقلين والمؤسسين وبائعي التجارة الإلكترونية.", whyTitle: "لماذا وُجد ProfitHub", whyText: "معظم الأعمال تُدار بالتخمين. ProfitHub يستبدل التخمين بالأرقام.", whoTitle: "لمن صُمم", whoText: "للمستقلين ومؤسسي SaaS وبائعي التجارة الإلكترونية وأصحاب الأعمال الصغيرة.", listTitle: "ما الذي يمكنك فعله مع ProfitHub", list: ["حساب الربح الحقيقي", "ضبط تسعير أفضل للعمل الحر", "فهم MRR ونمو SaaS", "تحليل تسرب الاشتراكات والتسرب", "تنظيم صفقات مشاركة الإيرادات", "اتخاذ قرارات أسرع ببيانات حقيقية"] },
  contact: { ...en.contact, badge: "تواصل مع ProfitHub", title: "تحدث مع فريق ProfitHub", intro: "نبني حاسبات مجانية وأدلة عملية وأدوات صفقات خفيفة. يسعدنا تواصلك.", primary: "التواصل الأساسي", response: "وقت الاستجابة المعتاد: خلال 1-2 يوم عمل.", topicsTitle: "ما الذي يمكنك التواصل معنا بشأنه" },
  contracts: { ...en.contracts, badge: "محرك صفقات ProfitHub", title: "مولدات العقود", intro: "أنشئ قوالب عقود عملية في دقائق.", note: "القوالب للدعم التشغيلي وليست استشارة قانونية.", comingSoon: "قريبًا", open: "فتح المولد" },
  privacy: { ...en.privacy, title: "سياسة الخصوصية", intro: "توضح هذه الصفحة البيانات التي يجمعها ProfitHub وكيفية استخدامها.", questionsTitle: "أسئلة الخصوصية", questionsText: "لأسئلة الخصوصية أو الطلبات، راسل contact@profithub.cloud أو زر", contactPage: "صفحة التواصل" },
  terms: { ...en.terms, title: "شروط الخدمة", intro: "توضح هذه الشروط كيفية استخدام حاسبات ProfitHub ومحتوى المدونة وأدوات العقود.", contactTitle: "التواصل", contactText: "يمكن إرسال الأسئلة حول هذه الشروط إلى contact@profithub.cloud. ويمكنك أيضًا استخدام", contactPage: "صفحة التواصل" },
  blog: { ...en.blog, badge: "مدونة ProfitHub", title: "رؤى حول الحاسبات والتسعير والربحية", intro: "اقرأ مقالات عملية حول التسعير والهوامش والإيرادات المتكررة وربحية المشاريع.", latestTitle: "أحدث المقالات", latestIntro: "استكشف الأدلة المرتبطة بحاسبات ProfitHub.", read: "اقرأ المقال" },
  calculators: { ...en.calculators, badge: "مركز حاسبات ProfitHub", title: "حاسبات أعمال مجانية للربحية والتسعير واتخاذ القرار", intro: "استكشف جميع حاسبات ProfitHub في مكان واحد.", open: "فتح", groups: [{ heading: "حاسبات التجارة الإلكترونية", intro: "تحقق من اقتصاد العرض وحسّن هامش المساهمة." }, { heading: "حاسبات SaaS", intro: "تابع جودة الإيراد المتكرر والتسرب وأثر الأولويات." }, { heading: "أدوات المستقلين والصفقات", intro: "حدد تسعيرًا مستدامًا وقيّم اقتصاديات المشاريع." }] },
};

const fr: Body = {
  ...en,
  about: { ...en.about, badge: "À propos de ProfitHub", title: "Conçu pour de meilleures décisions business basées sur les chiffres", intro: "ProfitHub est une collection de calculateurs business simples et puissants pour freelances, fondateurs et e-commerçants.", whyTitle: "Pourquoi ProfitHub existe", whyText: "La plupart des entreprises fonctionnent au ressenti. ProfitHub remplace les suppositions par des chiffres.", whoTitle: "Pour qui", whoText: "Freelances, fondateurs SaaS, vendeurs e-commerce et petites entreprises.", listTitle: "Ce que vous pouvez faire avec ProfitHub", list: ["Calculer le profit réel", "Définir un meilleur pricing freelance", "Comprendre le MRR SaaS et la croissance", "Analyser les fuites d’abonnement et le churn", "Structurer des accords de partage de revenus", "Décider plus vite avec des données réelles"] },
  contact: { ...en.contact, badge: "Contacter ProfitHub", title: "Parlez avec l'équipe ProfitHub", intro: "Nous créons des calculateurs gratuits, des guides pratiques et des outils de deals légers.", primary: "Contact principal", response: "Délai de réponse habituel : 1 à 2 jours ouvrés.", topicsTitle: "Sujets de contact" },
  contracts: { ...en.contracts, badge: "Moteur d'accords ProfitHub", title: "Générateurs de contrats", intro: "Créez des modèles de contrats pratiques en quelques minutes.", note: "Ces modèles sont fournis à titre opérationnel et ne constituent pas un conseil juridique.", comingSoon: "Bientôt disponible", open: "Ouvrir le générateur" },
  privacy: { ...en.privacy, title: "Politique de confidentialité", intro: "Cette page explique quelles données sont collectées et comment elles sont utilisées.", questionsTitle: "Questions de confidentialité", questionsText: "Pour toute question, écrivez à contact@profithub.cloud ou visitez notre", contactPage: "page de contact" },
  terms: { ...en.terms, title: "Conditions d'utilisation", intro: "Ces conditions décrivent l'utilisation des calculateurs, du blog et des outils de contrats.", contactTitle: "Contact", contactText: "Pour toute question, écrivez à contact@profithub.cloud ou utilisez notre", contactPage: "page de contact" },
  blog: { ...en.blog, badge: "Blog ProfitHub", title: "Calculateurs business, pricing et rentabilité", intro: "Lisez des articles pratiques sur le pricing, la marge et le revenu récurrent.", latestTitle: "Derniers articles", latestIntro: "Explorez les guides liés aux calculateurs ProfitHub.", read: "Lire l'article" },
  calculators: { ...en.calculators, badge: "Hub des calculateurs ProfitHub", title: "Calculateurs business gratuits pour la rentabilité et la décision", intro: "Explorez tous les calculateurs ProfitHub en un seul endroit.", open: "Ouvrir", groups: [{ heading: "Calculateurs e-commerce", intro: "Validez l'économie des offres et améliorez la marge." }, { heading: "Calculateurs SaaS", intro: "Suivez la qualité du revenu récurrent et les fuites." }, { heading: "Outils freelance & deals", intro: "Fixez des prix durables et évaluez la rentabilité des projets." }] },
};

const es: Body = {
  ...en,
  about: { ...en.about, badge: "Acerca de ProfitHub", title: "Creado para tomar mejores decisiones de negocio con datos", intro: "ProfitHub es una colección de calculadoras empresariales simples y potentes para freelancers, fundadores y ecommerce.", whyTitle: "Por qué existe ProfitHub", whyText: "Muchos negocios operan por intuición. ProfitHub reemplaza las suposiciones con números.", whoTitle: "Para quién es", whoText: "Freelancers, fundadores SaaS, vendedores ecommerce y pequeñas empresas.", listTitle: "Qué puedes hacer con ProfitHub", list: ["Calcular el beneficio real", "Definir mejores precios freelance", "Entender el MRR SaaS y el crecimiento", "Analizar fugas de suscripción y churn", "Estructurar acuerdos de reparto de ingresos", "Tomar decisiones más rápidas con datos reales"] },
  contact: { ...en.contact, badge: "Contactar a ProfitHub", title: "Habla con el equipo de ProfitHub", intro: "Creamos calculadoras gratuitas, guías prácticas y herramientas ligeras para acuerdos.", primary: "Contacto principal", response: "Tiempo de respuesta típico: 1–2 días hábiles.", topicsTitle: "Motivos para contactarnos" },
  contracts: { ...en.contracts, badge: "Motor de acuerdos ProfitHub", title: "Generadores de contratos", intro: "Crea plantillas de contratos prácticas en minutos.", note: "Estas plantillas son apoyo operativo y no asesoría legal.", comingSoon: "Próximamente", open: "Abrir generador" },
  privacy: { ...en.privacy, title: "Política de privacidad", intro: "Esta página explica qué datos se recopilan y cómo se usan.", questionsTitle: "Preguntas de privacidad", questionsText: "Para consultas de privacidad, escribe a contact@profithub.cloud o visita nuestra", contactPage: "página de contacto" },
  terms: { ...en.terms, title: "Términos del servicio", intro: "Estos términos describen el uso de calculadoras, blog y herramientas de contratos.", contactTitle: "Contacto", contactText: "Las preguntas sobre estos términos pueden enviarse a contact@profithub.cloud o usar nuestra", contactPage: "página de contacto" },
  blog: { ...en.blog, badge: "Blog de ProfitHub", title: "Calculadoras de negocio, precios y rentabilidad", intro: "Lee artículos prácticos sobre precios, márgenes e ingresos recurrentes.", latestTitle: "Últimos artículos", latestIntro: "Explora guías conectadas con las calculadoras de ProfitHub.", read: "Leer artículo" },
  calculators: { ...en.calculators, badge: "Hub de calculadoras ProfitHub", title: "Calculadoras de negocio gratis para rentabilidad, precios y decisiones", intro: "Explora todas las calculadoras de ProfitHub en un solo lugar.", open: "Abrir", groups: [{ heading: "Calculadoras de ecommerce", intro: "Valida la economía de tus ofertas y mejora margen." }, { heading: "Calculadoras SaaS", intro: "Sigue la calidad del ingreso recurrente y fugas." }, { heading: "Herramientas freelance y acuerdos", intro: "Define precios sostenibles y evalúa proyectos." }] },
};

const ru: Body = {
  ...en,
  about: { ...en.about, badge: "О ProfitHub", title: "Создано для более точных бизнес-решений на основе цифр", intro: "ProfitHub — набор простых и мощных бизнес-калькуляторов для фрилансеров, основателей и e-commerce команд.", whyTitle: "Зачем существует ProfitHub", whyText: "Многие бизнесы работают на догадках. ProfitHub заменяет догадки цифрами.", whoTitle: "Для кого", whoText: "Для фрилансеров, SaaS-основателей, продавцов e-commerce и малого бизнеса.", listTitle: "Что можно делать с ProfitHub", list: ["Считать реальную прибыль", "Устанавливать более точные фриланс-ставки", "Понимать SaaS MRR и рост", "Анализировать утечки подписок и отток", "Структурировать сделки revenue share", "Принимать более быстрые решения на основе данных"] },
  contact: { ...en.contact, badge: "Связаться с ProfitHub", title: "Свяжитесь с командой ProfitHub", intro: "Мы создаем бесплатные калькуляторы, практичные гайды и легкие инструменты для сделок.", primary: "Основной контакт", response: "Обычно отвечаем в течение 1–2 рабочих дней.", topicsTitle: "По каким вопросам писать" },
  contracts: { ...en.contracts, badge: "Deal Engine ProfitHub", title: "Генераторы контрактов", intro: "Создавайте практичные шаблоны контрактов за минуты.", note: "Шаблоны предназначены для операционной поддержки и не являются юридической консультацией.", comingSoon: "Скоро", open: "Открыть генератор" },
  privacy: { ...en.privacy, title: "Политика конфиденциальности", intro: "На этой странице объясняется, какие данные собираются и как используются.", questionsTitle: "Вопросы по конфиденциальности", questionsText: "По вопросам конфиденциальности пишите на contact@profithub.cloud или посетите", contactPage: "страницу контактов" },
  terms: { ...en.terms, title: "Условия использования", intro: "Эти условия описывают использование калькуляторов, блога и инструментов контрактов.", contactTitle: "Контакты", contactText: "Вопросы по этим условиям можно отправить на contact@profithub.cloud или через", contactPage: "страницу контактов" },
  blog: { ...en.blog, badge: "Блог ProfitHub", title: "Бизнес-калькуляторы, ценообразование и прибыльность", intro: "Читайте практические статьи о ценах, марже и регулярной выручке.", latestTitle: "Последние статьи", latestIntro: "Изучайте гайды, связанные с калькуляторами ProfitHub.", read: "Читать статью" },
  calculators: { ...en.calculators, badge: "Хаб калькуляторов ProfitHub", title: "Бесплатные бизнес-калькуляторы для прибыльности, цены и решений", intro: "Все калькуляторы ProfitHub в одном месте.", open: "Открыть", groups: [{ heading: "E-commerce калькуляторы", intro: "Проверяйте экономику оффера и улучшайте маржу." }, { heading: "SaaS калькуляторы", intro: "Отслеживайте качество регулярной выручки и утечки." }, { heading: "Инструменты для фриланса и сделок", intro: "Устанавливайте устойчивые цены и оценивайте проекты." }] },
};

export const publicPageBodies: Record<AppLocale, Body> = { en, ar, fr, es, ru };

export function getPublicPageBody(locale: AppLocale) {
  return publicPageBodies[locale];
}
