import Link from "next/link";

export const metadata = {
  title: "What Is a Revenue Share Agreement? How to Structure Fair Profit Splits",
  description:
    "Learn what a revenue share agreement is, how revenue sharing works, and how to structure fair percentage splits for creators, operators, agencies, and partners.",
};

export default function Page() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-16 text-gray-900">
      <h1 className="mb-6 text-4xl font-bold leading-tight">
        What Is a Revenue Share Agreement? How to Structure Fair Profit Splits
      </h1>

      <p className="mb-6 text-lg leading-8 text-gray-700">
        A revenue share agreement is a deal where two or more parties split
        income generated by a product, service, or business activity based on a
        defined percentage. It is one of the cleanest ways to align incentives
        when one side brings distribution, the other brings execution, and both
        want upside.
      </p>

      <p className="mb-6 leading-8 text-gray-700">
        Revenue sharing is common in creator businesses, affiliate partnerships,
        agencies, SaaS collaborations, licensing, and operator-led ventures. But
        most bad deals fail for the same reason: the split sounds simple, yet
        the economic structure is vague.
      </p>

      <h2 className="mb-4 mt-10 text-2xl font-semibold">
        How a revenue sharing model works
      </h2>

      <p className="mb-6 leading-8 text-gray-700">
        The basic model is straightforward. A business activity generates
        revenue, then that revenue is allocated based on an agreed percentage.
        For example:
      </p>

      <div className="mb-6 rounded-2xl border border-gray-200 bg-gray-50 p-5">
        <p className="text-lg font-semibold text-gray-900">
          If monthly revenue is $10,000 and the agreement is 70/30, one party
          receives $7,000 and the other receives $3,000.
        </p>
      </div>

      <p className="mb-6 leading-8 text-gray-700">
        That sounds simple, but a serious revenue share deal needs more
        precision.
      </p>

      <h2 className="mb-4 mt-10 text-2xl font-semibold">
        The key question: revenue share on gross or net?
      </h2>

      <p className="mb-6 leading-8 text-gray-700">
        This is where many partnerships break. Are you splitting gross revenue
        before costs, or net revenue after refunds, payment fees, ad spend, or
        operating expenses?
      </p>

      <ul className="mb-6 list-disc space-y-3 pl-6 leading-8 text-gray-700">
        <li>
          <strong>Gross revenue share</strong> is simpler and cleaner, but can be
          unfair if one side covers heavy costs.
        </li>
        <li>
          <strong>Net revenue share</strong> can be more realistic, but only if
          cost definitions are explicit and transparent.
        </li>
      </ul>

      <h3 className="mb-4 mt-8 text-xl font-semibold">
        Example
      </h3>

      <p className="mb-6 leading-8 text-gray-700">
        A creator and operator launch a digital product. The creator brings the
        audience. The operator builds the funnel, email flow, and fulfillment.
        If they agree to 50/50 on gross revenue, the operator may get squeezed
        if ad spend and software costs are high. If they agree to 50/50 on net
        revenue, they need exact rules for which costs count.
      </p>

      <h2 className="mb-4 mt-10 text-2xl font-semibold">
        When revenue share makes sense
      </h2>

      <ul className="mb-6 list-disc space-y-3 pl-6 leading-8 text-gray-700">
        <li>One partner brings distribution and the other brings execution</li>
        <li>Cash is limited but upside is strong</li>
        <li>Incentives need to stay aligned over time</li>
        <li>Performance matters more than fixed fees</li>
      </ul>

      <h2 className="mb-4 mt-10 text-2xl font-semibold">
        What should be included in the agreement
      </h2>

      <ul className="mb-6 list-disc space-y-3 pl-6 leading-8 text-gray-700">
        <li>Revenue definition</li>
        <li>Percentage split</li>
        <li>Payout schedule</li>
        <li>Refund handling</li>
        <li>Cost deductions, if any</li>
        <li>Ownership of assets and customer data</li>
        <li>Termination terms</li>
      </ul>

      <h2 className="mb-4 mt-10 text-2xl font-semibold">
        A fair split is not always equal
      </h2>

      <p className="mb-6 leading-8 text-gray-700">
        Equal is not the same as fair. A partner bringing an audience of 200,000
        qualified buyers is not contributing the same thing as a freelancer
        doing light admin work. The split should reflect leverage, risk,
        replacement difficulty, and long-term impact.
      </p>

      <p className="mb-6 leading-8 text-gray-700">
        Good operators do not ask only, “what percentage sounds nice?” They ask,
        “what economics make this partnership durable?”
      </p>

      <div className="mt-10 rounded-2xl border border-blue-200 bg-blue-50 p-6">
        <h3 className="mb-3 text-xl font-semibold text-gray-900">
          Model your split before agreeing
        </h3>
        <p className="mb-4 leading-8 text-gray-700">
          Use the ProfitHub Revenue Share Calculator to test percentage splits,
          compare payout outcomes, and structure cleaner partnership deals.
        </p>
        <Link
          href="/calculators/revenue-share"
          className="inline-flex items-center font-semibold text-blue-700 hover:text-blue-800"
        >
          Open Revenue Share Calculator →
        </Link>
      </div>
    </main>
  );
}