"use client";

import { parseContractText } from "@/lib/contract-formatting";

type ContractPaywallProps = {
  hasContract: boolean;
  contractText: string;
  isUnlocked: boolean;
  onUnlock: () => void;
};

function buildFileName(contractTitle?: string) {
  const date = new Date().toISOString().slice(0, 10);
  const safeTitle = (contractTitle || "contract")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)+/g, "");
  return `${safeTitle || "contract"}-${date}`;
}

function downloadTextFile(contractText: string) {
  const parsed = parseContractText(contractText);
  const blob = new Blob([contractText], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = `${buildFileName(parsed.title)}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);
}

async function downloadPdfFile(contractText: string) {
  const { jsPDF } = await import("jspdf");
  const parsed = parseContractText(contractText);

  const doc = new jsPDF({
    unit: "pt",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const marginLeft = 64;
  const marginRight = 64;
  const contentWidth = pageWidth - marginLeft - marginRight;
  const topMargin = 92;
  const bottomMargin = 72;
  const headerY = 42;
  const lineHeight = 18;

  let y = topMargin;

  const drawHeaderFooter = (pageNumber: number) => {
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(1);
    doc.line(marginLeft, 52, pageWidth - marginRight, 52);
    doc.line(marginLeft, pageHeight - 52, pageWidth - marginRight, pageHeight - 52);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(51, 65, 85);
    doc.text(parsed.title, marginLeft, headerY);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text(parsed.dateLine || `Date: ${new Date().toISOString().slice(0, 10)}`, pageWidth - marginRight, headerY, {
      align: "right",
    });

    doc.text("Generated by ProfitHub", marginLeft, pageHeight - 35);
    doc.text(`Page ${pageNumber}`, pageWidth - marginRight, pageHeight - 35, {
      align: "right",
    });
  };

  const addPage = () => {
    doc.addPage();
    y = topMargin;
    drawHeaderFooter(doc.getNumberOfPages());
  };

  const ensureSpace = (requiredHeight: number) => {
    if (y + requiredHeight > pageHeight - bottomMargin) {
      addPage();
    }
  };

  const writeParagraph = (text: string, options?: { bold?: boolean; align?: "left" | "center" }) => {
    const lines = doc.splitTextToSize(text, contentWidth);
    doc.setFont("helvetica", options?.bold ? "bold" : "normal");
    doc.setFontSize(options?.bold ? 12 : 11);
    doc.setTextColor(options?.bold ? 15 : 51, options?.bold ? 23 : 65, options?.bold ? 42 : 85);

    for (const line of lines) {
      ensureSpace(lineHeight);
      if (options?.align === "center") {
        doc.text(line, pageWidth / 2, y, { align: "center" });
      } else {
        doc.text(line, marginLeft, y);
      }
      y += lineHeight;
    }
  };

  drawHeaderFooter(1);

  if (parsed.subtitle) {
    writeParagraph(parsed.subtitle, { align: "center", bold: true });
    y += 4;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(15, 23, 42);
  ensureSpace(30);
  doc.text(parsed.title, pageWidth / 2, y, { align: "center" });
  y += 30;

  if (parsed.dateLine) {
    writeParagraph(parsed.dateLine, { align: "center" });
    y += 6;
  }

  if (parsed.intro) {
    writeParagraph(parsed.intro);
    y += 8;
  }

  for (const section of parsed.sections) {
    ensureSpace(30);
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(1);
    doc.line(marginLeft, y - 6, pageWidth - marginRight, y - 6);

    writeParagraph(section.heading, { bold: true });

    for (const paragraph of section.paragraphs) {
      if (paragraph.startsWith("- ")) {
        writeParagraph(`• ${paragraph.slice(2)}`);
      } else {
        writeParagraph(paragraph);
      }
    }

    y += 6;
  }

  for (const note of parsed.trailingNotes) {
    ensureSpace(24);
    doc.setDrawColor(226, 232, 240);
    doc.line(marginLeft, y, pageWidth - marginRight, y);
    y += 18;
    writeParagraph(note);
  }

  doc.save(`${buildFileName(parsed.title)}.pdf`);
}

export default function ContractPaywall({
  hasContract,
  contractText,
  isUnlocked,
  onUnlock,
}: ContractPaywallProps) {
  return (
    <section className="rounded-3xl border border-slate-200 bg-white shadow-sm">
      <div className="border-b border-slate-200 px-6 py-5">
        <h2 className="text-xl font-semibold text-slate-900">
          Download Access
        </h2>
        <p className="mt-2 text-sm leading-6 text-slate-600">
          Preview first, then unlock the document download.
        </p>
      </div>

      <div className="p-6">
        {!hasContract ? (
          <div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 px-6 py-8 text-center">
            <p className="text-sm text-slate-600">
              Generate a contract first to continue.
            </p>
          </div>
        ) : isUnlocked ? (
          <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6">
            <div className="flex flex-col gap-6">
              <div>
                <p className="text-sm font-semibold uppercase tracking-[0.16em] text-emerald-700">
                  Access Unlocked
                </p>
                <h3 className="mt-2 text-lg font-semibold text-slate-900">
                  Your contract is ready
                </h3>
                <p className="mt-2 text-sm leading-6 text-slate-700">
                  You can now download your contract as a TXT file or a PDF
                  document.
                </p>
              </div>

              <div className="flex flex-col gap-3 sm:flex-row">
                <button
                  type="button"
                  onClick={() => downloadTextFile(contractText)}
                  className="inline-flex items-center justify-center rounded-2xl bg-slate-900 px-5 py-3 text-sm font-semibold text-white transition hover:bg-slate-800"
                >
                  Download TXT
                </button>

                <button
                  type="button"
                  onClick={() => downloadPdfFile(contractText)}
                  className="inline-flex items-center justify-center rounded-2xl border border-slate-300 bg-white px-5 py-3 text-sm font-semibold text-slate-900 transition hover:bg-slate-50"
                >
                  Download PDF
                </button>
              </div>
            </div>
          </div>
        ) : (
          <div className="rounded-2xl border border-amber-200 bg-amber-50 p-6">
            <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
              <div>
                <p className="text-sm font-semibold uppercase tracking-[0.16em] text-amber-700">
                  Locked
                </p>
                <h3 className="mt-2 text-lg font-semibold text-slate-900">
                  Unlock this contract for $1
                </h3>
                <p className="mt-2 text-sm leading-6 text-slate-700">
                  This is the MVP lock state. Real payment will be connected
                  next. For now, use the button below to simulate access.
                </p>
              </div>

              <button
                type="button"
                onClick={onUnlock}
                className="inline-flex items-center justify-center rounded-2xl bg-slate-900 px-5 py-3 text-sm font-semibold text-white transition hover:bg-slate-800"
              >
                Simulate Unlock
              </button>
            </div>
          </div>
        )}
      </div>
    </section>
  );
}
